Update test-token.yaml

diff --git a/.github/workflows/test-token.yaml b/.github/workflows/test-token.yaml
--- a/.github/workflows/test-token.yaml
+++ b/.github/workflows/test-token.yaml
@@ -26,3 +26,6 @@ jobs:
         echo "::set-output name=REPO_CLAIM::$JWT"
     - name: Print Sub Claim
       run: echo "Subject Claim of Repo - ${{ steps.generateClaim.outputs.REPO_CLAIM }}"
+    - name: Check for Sub Claim Match
+      if: ${{ steps.generateClaim.outputs.REPO_CLAIM != github.event.inputs.subjectClaim }}
+      run: echo "::error::Subject Claim mismatch found" && exit 1
